### ISSUE TITLE
[Feature Request]: Provide Docker Image

### ISSUE THREAD

**Issue by jimlee2048** [j1g5awi/simpread-sync#1]
容器化将能极大的便利项目的部署使用，希望能够提供 Docker Image，允许通过启动命令或 `docker-compose` 传递环境变量的方式配置参数。

**Comment by j1g5awi** [comment]
我这项目编译后就一单文件，想请问上 Docker 便利在哪？

**Comment by jimlee2048** [comment]
作为docker综合征患者，我个人Self-Hosted的服务基本上都是通过docker容器部署的，我认为使用docker来部署有以下理由：
- docker是主流的、通用性的、标准化的部署方式，适应部分习惯用docker部署服务的用户需要（比如我）
- 基于docker的通用interfaces，能够利用标准化的`docker-compose.yml`定义好目录挂载、端口映射和用来传递配置参数的环境变量，便于服务的部署与整体迁移
- 提供隔离、统一的环境，避免在不同平台上部署时，由于不同的kernal/依赖库情况可能存在的奇怪问题
- 资源限制，便于控制有限权限（如端口暴露）
- 方便更新或回滚版本，可以配合 [watchtower](https://github.com/containrrr/watchtower) 实现自动版本更新
- k8s集群编排的可能性

我个人不了解go开发，可能有不合理的地方，还请批评指正

**Comment by jimlee2048** [comment]
这里分享下我个人计划的使用场景：
我希望在我的群晖nas上通过docker部署简悦同步助手命令行，实现以下需求：
  - 归档文章：配合自动化任务，实现加入稍后读后，自动保存markdown文件到群晖nas的特定文件夹下，以供随时查阅与调用
  - 反代访问：出于安全考虑，我不希望直接在群晖宿主机直接暴露同步助手的访问端口，而是基于docker的虚拟网桥，在`docker-compose.yml`中配合[Nginx Proxy Manager](https://nginxproxymanager.com/)或[Traefik](https://doc.traefik.io/traefik/)进行访问可控的反代，提高远程调用的安全性，可参考[这篇介绍](https://nginxproxymanager.com/advanced-config/#best-practice-use-a-docker-network)
  - 同步助手的自动更新：配合[watchtower](https://github.com/containrrr/watchtower) ，自动更新到最新版本
  - 同步助手的管理维护：能够通过已有的[Portainer](https://www.portainer.io/)随时管理同步助手容器，运行异常时便于查看logs&尝试重启，还可利用上docker的[healthcheck](https://docs.docker.com/engine/reference/builder/#healthcheck)直观了解同步助手的运行状态

**Comment by j1g5awi** [comment]
你第一条回复里的理由我基本都了解，其实我想问的是你第二条回复的内容，即「本项目上 Docker 和不上 Docker 有何区别」。

编译 docker 镜像其实不是什么难事，本周末大概就能完成。

**Comment by Kenshin** [comment]
@j1g5awi 

好，搞定后在 Telegram 上联系我，好久没有再介绍命令行的功能了。

@jimlee2002 

搞定 Docker 版后，能否把 https://github.com/j1g5awi/simpread-sync/issues/1#issuecomment-1193106967 扩写下？我会发到 https://github.com/Kenshin/simpread/discussions/2085 里面，工喜欢折腾的简悦用户使用。

**Comment by jimlee2048** [comment]
> @j1g5awi
> 
> 好，搞定后在 Telegram 上联系我，好久没有再介绍命令行的功能了。
> 
> @jimlee2002
> 
> 搞定 Docker 版后，能否把 [#1 (comment)](https://github.com/j1g5awi/simpread-sync/issues/1#issuecomment-1193106967) 扩写下？我会发到 [Kenshin/simpread#2085](https://github.com/Kenshin/simpread/discussions/2085) 里面，工喜欢折腾的简悦用户使用。

没问题，我很乐意写一篇群晖中部署使用的简要指南。😄
我计划在文中，只会介绍到如何在群晖中使用docker部署配置同步助手，以及如何使用watchtower配置容器的自动更新；更加进阶的反代访问和[Portainer](https://www.portainer.io/)的使用就不打算涉及了，超出了介绍同步助手的范畴，会在文末提供一个研究方向，供读者去自行探索。

**Comment by jimlee2048** [comment]
> 你第一条回复里的理由我基本都了解，其实我想问的是你第二条回复的内容，即「本项目上 Docker 和不上 Docker 有何区别」。
> 
> 编译 docker 镜像其实不是什么难事，本周末大概就能完成。

感谢！关于docker image，希望还能提供arm架构的，群晖和威联通都有使用arm架构cpu的入门型号，也有一些人是在装了openwrt/官方提供docker的硬路由上跑的docker😂

**Comment by j1g5awi** [comment]
https://github.com/j1g5awi/simpread-sync/pkgs/container/simpread-sync

你可以测试下，仓库下提供 docker-compose.yml，请修改 `command: /usr/bin/simpread-sync --sync-path /data` 处进行配置。

如果不需要使用 pandoc（导出 epub），wkhtml2pdf（导出 pdf），可以使用更轻量的 `alpine` 镜像。

**Comment by Kenshin** [comment]
> 没问题，我很乐意写一篇群晖中部署使用的简要指南。😄

@jimlee2002  那就太棒了，主要涉及到使用 docker 简悦的用法就好，涉及到更深的内容让有需要的用户自己探索。

成文后可以直接发到 https://github.com/Kenshin/simpread/discussions/new 后续我会优化。

**Comment by jimlee2048** [comment]
> https://github.com/j1g5awi/simpread-sync/pkgs/container/simpread-sync
> 
> 你可以测试下，仓库下提供 docker-compose.yml，请修改 `command: /usr/bin/simpread-sync --sync-path /data` 处进行配置。

刚才在Win上的测试环境中简单测试了下：
- 开启容器后，需要去简悦的设置面板同步下手动同步浏览器配置文件到同步助手容器内
- 点击单独的导出动作，可以正常的输出文件
- 自动化任务不生效：
  ![image](https://user-images.githubusercontent.com/21117946/180610657-f4cb458d-9379-440b-abad-b3584a83dffb.png)
  设置了加入稍后读后自动触发自动导出的自动化任务，添加任意文章到稍后读后，同步助手并没有自动导出，只是同步了浏览器的配置文件
  ```
  simpread-sync-simpread-sync-1 | 2022/07/23 15:09:10 sync config from browser
  ```
  将自动化任务设置为手动触发后，手动在动作中触发该自动化任务，可以自动导出
  ```
  simpread-sync-simpread-sync-1 | 2022/07/23 15:07:26 save file: 成功脱坑群晖入坑威联通.md
  simpread-sync-simpread-sync-1 | 2022/07/23 15:07:28 save file: 成功脱坑群晖入坑威联通.html
  ```
- 简悦无法设置同步助手的地址，待会我去简悦仓库那边开个FR的issue

**Comment by j1g5awi** [comment]
> 开启容器后，需要去简悦的设置面板同步下手动同步浏览器配置文件到同步助手容器内。

这本来就是初次使用同步助手必要的步骤：https://github.com/Kenshin/simpread/discussions/2754

> 设置了加入稍后读后自动触发自动导出的自动化任务，添加任意文章到稍后读后，同步助手并没有自动导出，只是同步了浏览器的配置文件

简悦扩展端的问题，在动作栏里点击保存到稍后读的按钮一直触发不了自动化流程：https://github.com/Kenshin/simpread/discussions/2362

**Comment by jimlee2048** [comment]
> > 开启容器后，需要去简悦的设置面板同步下手动同步浏览器配置文件到同步助手容器内。
> 
> 这本来就是初次使用同步助手必要的步骤：[Kenshin/simpread#2754](https://github.com/Kenshin/simpread/discussions/2754)
> 
> > 设置了加入稍后读后自动触发自动导出的自动化任务，添加任意文章到稍后读后，同步助手并没有自动导出，只是同步了浏览器的配置文件
> 
> 简悦扩展端的问题，在动作栏里点击保存到稍后读的按钮一直触发不了自动化流程：[Kenshin/simpread#2362](https://github.com/Kenshin/simpread/discussions/2362)

好的，那我目前使用上没有遇到问题了，就是希望能够直接通过环境变量传参数，不用再挂一个`congig.json`，这样就更方便配置了。

**Comment by Kenshin** [comment]
> 好的，那我目前使用上没有遇到问题了，就是希望能够直接通过环境变量传参数，不用再挂一个congig.json，这样就更方便配置了。

没问题就好

PS：端口号的 Feature 早就记录了。

话说，别忘记写篇内容（教程，分享均可）直接发到 https://github.com/Kenshin/simpread/discussions/new 即可。

**Comment by j1g5awi** [comment]
已经支持环境变量配置，需要注意大写格式。比如 `config.json` 中的 `syncPath` 配置项，在环境变量里需要写成 `SYNCPATH`。

`enhancedOutput` 则比较特殊，不能直接使用 `ENHANCEDOUTPUT` 配置，而是使用 `SIMPREAD_{扩展名}PATH` 作为环境变量的名称来配置不同扩展名的导出路径。比如 `{"extension":"md", "path":"/Users/xxxx/xxxx/Obsidian/SimpRead"}` 需要写成 `SIMPREAD_MDPATH=/Users/xxxx/xxxx/Obsidian/SimpRead`。

**Comment by Kenshin** [comment]
@j1g5awi 

Docker 没问题的话，也可以直接发到 https://github.com/Kenshin/simpread/discussions/new 简单说明下即可。

如果 @jimlee2002 这几天能搞定的话，等文章出了一起发也行。

**Comment by jimlee2048** [comment]
> > 好的，那我目前使用上没有遇到问题了，就是希望能够直接通过环境变量传参数，不用再挂一个congig.json，这样就更方便配置了。
> 
> 没问题就好
> 
> PS：端口号的 Feature 早就记录了。
> 
> 话说，别忘记写篇内容（教程，分享均可）直接发到 https://github.com/Kenshin/simpread/discussions/new 即可。

好的，其实我想等 https://github.com/Kenshin/simpread/issues/4247 出来后再一起介绍会比较好，无法自定义使用的同步助手地址的话，要使用远程部署的同步助手就还是只能配置一遍相对复杂的端口转发，个人觉得通过端口转发到本地回环地址实现使用远程同步助手的方式不太优雅，同时这样下来远程部署的docker就显得没那么有价值了，本质还是和 https://github.com/Kenshin/simpread/discussions/3898 一样，只是换了种部署方式。🤔

**Comment by jimlee2048** [comment]
> 已经支持环境变量配置，需要注意大写格式。比如 `config.json` 中的 `syncPath` 配置项，在环境变量里需要写成 `SYNCPATH`。
> 
> `enhancedOutput` 则比较特殊，不能直接使用 `ENHANCEDOUTPUT` 配置，而是使用 `SIMPREAD_{扩展名}PATH` 作为环境变量的名称来配置不同扩展名的导出路径。比如 `{"extension":"md", "path":"/Users/xxxx/xxxx/Obsidian/SimpRead"}` 需要写成 `SIMPREAD_MDPATH=/Users/xxxx/xxxx/Obsidian/SimpRead`。

好的，我待会来试试看，感谢！😄

**Comment by jimlee2048** [comment]
> 已经支持环境变量配置，需要注意大写格式。比如 `config.json` 中的 `syncPath` 配置项，在环境变量里需要写成 `SYNCPATH`。
> 
> `enhancedOutput` 则比较特殊，不能直接使用 `ENHANCEDOUTPUT` 配置，而是使用 `SIMPREAD_{扩展名}PATH` 作为环境变量的名称来配置不同扩展名的导出路径。比如 `{"extension":"md", "path":"/Users/xxxx/xxxx/Obsidian/SimpRead"}` 需要写成 `SIMPREAD_MDPATH=/Users/xxxx/xxxx/Obsidian/SimpRead`。

一切工作正常，辛苦了！😄
关于docker镜像，我还有一些想法建议：

- 允许通过环境变量设置容器时区，比如：
  ```
  TZ=Asia/Shanghai
  ```
  使用场景：
  - 希望容器以本地时间戳输出日志
  - 在发送的邮件标题中使用本地的时间戳
  
- 允许通过环境变量手动设置容器导出文件使用的user namespace，比如：
  ```
  PUID=1000
  PGID=1000
  ```
  使用场景：
  - 不希望输出文件夹由默认的root进行管理
  - 在群晖上规避可能存在的文件权限问题

- 上传到 Docker Hub 方便镜像的查找与使用，并提供多平台的镜像

- 使用 alpine 打包镜像，缩小镜像体积

- 传递给docker的全局变量名可以使用下划线命名法，以提高辨识度与易读性，比如：
  ```
  SYNC_PATH=/data
  OUTPUT_PATH=/data/output
  SMTP_HOST=
  SMTP_PORT=465
  SMTP_USERNAME=
  SMTP_PASSWORD=
  MAIL_TITLE="[简悦] - {{title}}"
  ```
  
- 结合下划线命名法，部分全局变量名我认为可以修改下，以便于使用者理解，以下是我的个人想法：
  ```
  # PORT=7026 >>>
  LISTEN_PORT=7026 
  # 与 `SMTP_PORT` 相区分
  
  # SIMPREAD_{扩展名}PATH=/Users/xxxx/xxxx/Obsidian/SimpRead >>>
  OUTPUT_PATH_{扩展名}=/Users/xxxx/xxxx/Obsidian/SimpRead 
  # 对应 `OUTPUT_PATH`
  
  # RECEIVERMAIL=  >>>
  MAIL_RECEIVER=
  # KINDLEMAIL=  >>>
  MAIL_KINDLE=
  # 对应 `MAIL_TITLE`
  ```

**Comment by jimlee2048** [comment]
噢对了，关于Golang项目打包为多平台二进制文件并发布到Github Release和Docker Hub，今天我看到了这个指南，希望能有帮助：
https://github.com/LeslieLeung/go-multiplatform-docker

**Comment by jimlee2048** [comment]
> > 已经支持环境变量配置，需要注意大写格式。比如 `config.json` 中的 `syncPath` 配置项，在环境变量里需要写成 `SYNCPATH`。
> > `enhancedOutput` 则比较特殊，不能直接使用 `ENHANCEDOUTPUT` 配置，而是使用 `SIMPREAD_{扩展名}PATH` 作为环境变量的名称来配置不同扩展名的导出路径。比如 `{"extension":"md", "path":"/Users/xxxx/xxxx/Obsidian/SimpRead"}` 需要写成 `SIMPREAD_MDPATH=/Users/xxxx/xxxx/Obsidian/SimpRead`。
> 
> 一切工作正常，辛苦了！😄 关于docker镜像，我还有一些想法建议：
> 
> * 允许通过环境变量设置容器时区，比如：
>   ```
>   TZ=Asia/Shanghai
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   使用场景：
>   
>   * 希望容器以本地时间戳输出日志
>   * 在发送的邮件标题中使用本地的时间戳
> * 允许通过环境变量手动设置容器导出文件使用的user namespace，比如：
>   ```
>   PUID=1000
>   PGID=1000
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   使用场景：
>   
>   * 不希望输出文件夹由默认的root进行管理
>   * 在群晖上规避可能存在的文件权限问题
> * 上传到 Docker Hub 方便镜像的查找与使用，并提供多平台的镜像
> * 使用 alpine 打包镜像，缩小镜像体积
> * 传递给docker的全局变量名可以使用下划线命名法，以提高辨识度与易读性，比如：
>   ```
>   SYNC_PATH=/data
>   OUTPUT_PATH=/data/output
>   SMTP_HOST=
>   SMTP_PORT=465
>   SMTP_USERNAME=
>   SMTP_PASSWORD=
>   MAIL_TITLE="[简悦] - {{title}}"
>   ```
> * 结合下划线命名法，部分全局变量名我认为可以修改下，以便于使用者理解，以下是我的个人想法：
>   ```
>   # PORT=7026 >>>
>   LISTEN_PORT=7026 
>   # 与 `SMTP_PORT` 相区分
>   
>   # SIMPREAD_{扩展名}PATH=/Users/xxxx/xxxx/Obsidian/SimpRead >>>
>   OUTPUT_PATH_{扩展名}=/Users/xxxx/xxxx/Obsidian/SimpRead 
>   # 对应 `OUTPUT_PATH`
>   
>   # RECEIVERMAIL=  >>>
>   MAIL_RECEIVER=
>   # KINDLEMAIL=  >>>
>   MAIL_KINDLE=
>   # 对应 `MAIL_TITLE`
>   ```

唔不好意思，突然意识到这好像算是新FR了，我需要开条新issue嘛🤥

**Comment by j1g5awi** [comment]
不用开新 Issue，这都与 Docker 相关。

> 允许通过环境变量设置容器时区

本来就支持。

> 允许通过环境变量手动设置容器导出文件使用的user namespace

先把宿主机的导出文件夹创建好，然后在 docker-compose.yaml 中添加

```yaml
    user: 1000:1000
    volumes:
      - ~/simpread:/data
```

> 上传到 Docker Hub 方便镜像的查找与使用，并提供多平台的镜像

不会传到 Docker Hub，ghcr.io 够用了；arm64 镜像已发布，由于我目前手上没有相应环境，需要你帮忙测试下。

> 使用 alpine 打包镜像，缩小镜像体积

由于需要安装 pandoc 和 wkhtml2pdf，所以使用更方便的 debian 镜像，如不需要这些功能可以拉取 `alpine` 分支。

```sh
docker pull ghcr.io/j1g5awi/simpread-sync:alpine
```

> 传递给docker的全局变量名可以使用下划线命名法，以提高辨识度与易读性

| config.json    | 命令行参数         | 环境变量                |
| -------------- | ------------------ | ----------------------- |
| port           | --port             | LISTEN_PORT             |
| syncPath       | --sync-path        | SYNC_PATH               |
| outputPath     | --output-path      | OUTPUT_PATH             |
| autoRemove     | --auto-remove      | AUTO_REMOVE             |
| smtpHost       | --smtp-host        | SMTP_HOST               |
| smtpPort       | --smtp-port        | SMTP_PORT               |
| smtpUsername   | --smtp-username    | SMTP_USERNAME           |
| smtpPassword   | --smtp-password    | SMTP_PASSWORD           |
| mailTitle      | --mail-title       | MAIL_TITLE              |
| receiverMail   | --receiver-mail    | MAIL_RECEIVER           |
| kindleMail     | --kindle-mail      | MAIL_KINDLE             |
| enhancedOutput |                    |                         |
|                | --{extension}-path | OUTPUT_PATH_{extension} |

**Comment by Kenshin** [comment]
@jimlee2002 

> 好的，其实我想等 https://github.com/Kenshin/simpread/issues/4247 出来后再一起介绍会比较好，无法自定义使用的同步助手地址的话，要使用远程部署的同步助手就还是只能配置一遍相对复杂的端口转发。

端口定制化的功能短期内没法实现，因为要升级扩展端，所以才叫 Feature

**Comment by jimlee2048** [comment]
> 不用开新 Issue，这都与 Docker 相关。
> 
> > 允许通过环境变量设置容器时区
> 
> 本来就支持。
> 
> > 允许通过环境变量手动设置容器导出文件使用的user namespace
> 
> 先把宿主机的导出文件夹创建好，然后在 docker-compose.yaml 中添加
> 
> ```yaml
>     user: 1000:1000
>     volumes:
>       - ~/simpread:/data
> ```
> 
> > 上传到 Docker Hub 方便镜像的查找与使用，并提供多平台的镜像
> 
> 不会传到 Docker Hub，ghcr.io 够用了；arm64 镜像已发布，由于我目前手上没有相应环境，需要你帮忙测试下。
> 
> > 使用 alpine 打包镜像，缩小镜像体积
> 
> 由于需要安装 pandoc 和 wkhtml2pdf，所以使用更方便的 debian 镜像，如不需要这些功能可以拉取 `alpine` 分支。
> 
> ```shell
> docker pull ghcr.io/j1g5awi/simpread-sync:alpine
> ```
> 
> > 传递给docker的全局变量名可以使用下划线命名法，以提高辨识度与易读性
> 
> config.json	命令行参数	环境变量
> port	--port	LISTEN_PORT
> syncPath	--sync-path	SYNC_PATH
> outputPath	--output-path	OUTPUT_PATH
> autoRemove	--auto-remove	AUTO_REMOVE
> smtpHost	--smtp-host	SMTP_HOST
> smtpPort	--smtp-port	SMTP_PORT
> smtpUsername	--smtp-username	SMTP_USERNAME
> smtpPassword	--smtp-password	SMTP_PASSWORD
> mailTitle	--mail-title	MAIL_TITLE
> receiverMail	--receiver-mail	MAIL_RECEIVER
> kindleMail	--kindle-mail	MAIL_KINDLE
> enhancedOutput		
> --{extension}-path	OUTPUT_PATH_{extension}

感谢！抱歉这两天有些事没空上Github看，我现在试试看！

**Comment by jimlee2048** [comment]
> @jimlee2002
> 
> > 好的，其实我想等 [Kenshin/simpread#4247](https://github.com/Kenshin/simpread/issues/4247) 出来后再一起介绍会比较好，无法自定义使用的同步助手地址的话，要使用远程部署的同步助手就还是只能配置一遍相对复杂的端口转发。
> 
> 端口定制化的功能短期内没法实现，因为要升级扩展端，所以才叫 Feature

好吧，那我这两天抽空先帮忙写一下Docker镜像的使用方法吧😊

**Comment by jimlee2048** [comment]
> 不用开新 Issue，这都与 Docker 相关。
> 
> > 允许通过环境变量设置容器时区
> 
> 本来就支持。
> 
> > 允许通过环境变量手动设置容器导出文件使用的user namespace
> 
> 先把宿主机的导出文件夹创建好，然后在 docker-compose.yaml 中添加
> 
> ```yaml
>     user: 1000:1000
>     volumes:
>       - ~/simpread:/data
> ```
> 
> > 上传到 Docker Hub 方便镜像的查找与使用，并提供多平台的镜像
> 
> 不会传到 Docker Hub，ghcr.io 够用了；arm64 镜像已发布，由于我目前手上没有相应环境，需要你帮忙测试下。
> 
> > 使用 alpine 打包镜像，缩小镜像体积
> 
> 由于需要安装 pandoc 和 wkhtml2pdf，所以使用更方便的 debian 镜像，如不需要这些功能可以拉取 `alpine` 分支。
> 
> ```shell
> docker pull ghcr.io/j1g5awi/simpread-sync:alpine
> ```
> 
> > 传递给docker的全局变量名可以使用下划线命名法，以提高辨识度与易读性
> 
> config.json	命令行参数	环境变量
> port	--port	LISTEN_PORT
> syncPath	--sync-path	SYNC_PATH
> outputPath	--output-path	OUTPUT_PATH
> autoRemove	--auto-remove	AUTO_REMOVE
> smtpHost	--smtp-host	SMTP_HOST
> smtpPort	--smtp-port	SMTP_PORT
> smtpUsername	--smtp-username	SMTP_USERNAME
> smtpPassword	--smtp-password	SMTP_PASSWORD
> mailTitle	--mail-title	MAIL_TITLE
> receiverMail	--receiver-mail	MAIL_RECEIVER
> kindleMail	--kindle-mail	MAIL_KINDLE
> enhancedOutput		
> --{extension}-path	OUTPUT_PATH_{extension}

工作正常，感谢作者！我这两天抽空帮忙补充下Docker部署的ReadMe吧，弄好后我发PR你看看😄

**Comment by Kenshin** [comment]
@jimlee2002 

okay 我等你的使用方法。

**Comment by jimlee2048** [comment]
https://github.com/Kenshin/simpread/discussions/4312
写好了，错漏之处还请斧正👀

**Comment by jimlee2048** [comment]
#3

**Comment by Kenshin** [comment]
@jimlee2002 

> [Kenshin/simpread#4312](https://github.com/Kenshin/simpread/discussions/4312) 写好了，错漏之处还请斧正👀

嗨，我今天早上优化了下文章结构，但忘记在这里告诉你了 😂

因为不支持 `[xxx](#xxx)` 方案，所以我增加了类似 https://github.com/Kenshin/simpread/discussions/4312#discussioncomment-3304515 这样的结构。

PS：你的补足我已经加上了，然后删除了你的内容。
