### ISSUE TITLE
使用md+assets插件保存文章图片报错

### ISSUE THREAD

**Issue by naah69** [j1g5awi/simpread-sync#4]
使用md+asserts方式导出时会有以下问题：
1. http导出图片时，证书未知
![image](https://user-images.githubusercontent.com/25682169/220931960-a8e35551-2129-4aa3-9c2f-d04f5307b2e1.png)

2. 使用base64导出时，请求体太大
![image](https://user-images.githubusercontent.com/25682169/220932039-6cf8c9e2-94f4-468b-a0cf-e30193f92406.png)

**Comment by Kenshin** [comment]
把出问题的 URL 给我看下。

另外，多测试些不同的页面。

**Comment by naah69** [comment]
测了几个页面都是这样的，我在浏览器控制台看不到插件的请求，请问有什么方法能看到这个请求接口吗
![image](https://user-images.githubusercontent.com/25682169/220944723-4ef660a6-aa8e-4c78-ba9d-9060864a508d.png)

**Comment by naah69** [comment]
感觉可能需要在http请求时忽略证书校验
```go
 tr := &http.Transport{
        TLSClientConfig:    &tls.Config{InsecureSkipVerify: true},
    }
    client := &http.Client{Transport: tr}
```

**Comment by naah69** [comment]
pr in https://github.com/j1g5awi/simpread-sync/pull/5

**Comment by j1g5awi** [comment]
严格来说这是网站自己的问题，不过鉴于某些网站确实会出现长期不更新证书的情况还是合并吧。

**Comment by naah69** [comment]
> 
 我试了下微信公众号文章和掘金的，都不行😂
